name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    container:
      image: instrumentisto/flutter:3.29.2

    env:
      CHROME_EXECUTABLE: /usr/bin/chromedriver
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64/
      ANDROID_HOME: /opt/android-sdk-linux
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LANGUAGE: en_US:en
      ANDROID_SDK_ROOT: /opt/android-sdk-linux
      ANDROID_SDK_HOME: /opt/android-sdk-linux
      ANDROID_NDK_HOME: /opt/android-sdk-linux/ndk/23.1.7779620
      ANDROID_SDK_TOOLS_VERSION: 11076708
      ANDROID_PLATFORM_VERSION: 35
      VERSION_NDK: 23.1.7779620
      VERSION_SDK: 11076708
      ANDROID_BUILD_TOOLS_VERSION: 35.0.0
      FLUTTER_HOME: /usr/local/flutter
      FLUTTER_VERSION: 3.29.2
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk-linux/cmdline-tools/latest/bin:/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/emulator:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk-linux/cmdline-tools/latest/bin:/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/emulator:/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin
      FLET_ANDROID_SIGNING_KEY_PASSWORD: "${{ secrets.ANDROID_KEY_PASSWORD }}"
      FLET_ANDROID_SIGNING_KEY_STORE_PASSWORD: "${{ secrets.ANDROID_STORE_PASSWORD }}"
      FLET_ANDROID_SIGNING_KEY_ALIAS: "upload"

    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        run: |
          git config --global --add safe.directory /usr/local/flutter
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > upload-keystore.jks
          flutter --version
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver python3-pip openjdk-17-jdk zenity unzip
          yes | sdkmanager --licenses || true
          sdkmanager "ndk;23.1.7779620"
          pip install --no-cache-dir --break-system-packages "flet[all]==0.28.3"

      - name: Build FFmpeg and FFprobe with ffmpeg-android-maker
        run: |
          git clone https://github.com/Javernaut/ffmpeg-android-maker.git
          cd ffmpeg-android-maker
          ./ffmpeg-android-maker.sh --target-abis "armeabi-v7a" > /dev/null;
          ls build
          ls build/*/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg
          path: ./ffmpeg-android-maker/build/

          #./init-ffmpeg.sh  # инициализация (скачивание исходников)
          #./build-ffmpeg.sh # сборка ffmpeg и ffprobe
          
          # После сборки бинарники будут в директории:
          # ffmpeg-android-maker/ffmpeg/build/ffmpeg-android-x86_64/ffmpeg (пример)
          
          # Копируем ffmpeg и ffprobe в нужное место проекта (пример, изменить под свой путь)
          #mkdir -p ../android/app/src/main/jniLibs/arm64-v8a/
          #cp ffmpeg/build/ffmpeg-android-arm64-v8a/ffmpeg ../android/app/src/main/jniLibs/arm64-v8a/
          #cp ffmpeg/build/ffmpeg-android-arm64-v8a/ffprobe ../android/app/src/main/jniLibs/arm64-v8a/
          
          #cd ..

#      - name: Build APK
#        run: |
#          flet build apk --arch armeabi-v7a --compile-packages --compile-app --cleanup-app
#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: fetchfile
#          path: build/apk/*
#          compression-level: 0
