name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    container:
      image: instrumentisto/flutter:3.29.2

    env:
      CHROME_EXECUTABLE: /usr/bin/chromedriver
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64/
      ANDROID_HOME: /opt/android-sdk-linux
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LANGUAGE: en_US:en
      ANDROID_SDK_ROOT: /opt/android-sdk-linux
      ANDROID_SDK_TOOLS_VERSION: 11076708
      ANDROID_PLATFORM_VERSION: 35
      ANDROID_BUILD_TOOLS_VERSION: 35.0.0
      FLUTTER_HOME: /usr/local/flutter
      FLUTTER_VERSION: 3.29.2
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk-linux/cmdline-tools/latest/bin:/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/emulator:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/android-sdk-linux/cmdline-tools/latest/bin:/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/emulator:/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin

    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        run: |
          git config --global --add safe.directory /usr/local/flutter
          echo "ls /usr/lib/jvm/"
          ls /usr/lib/jvm/
          flutter --version
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver python3-pip openjdk-17-jdk zenity libmimalloc-dev libmimalloc2.0 libmpv-dev #python3-pyjnius
          yes | sdkmanager --licenses || true
          pip install --no-cache-dir --break-system-packages "flet[all]"

      - name: Build APK
        run: flet build apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fetchfile.apk
          path: build/apk/
